#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v4
# autospec commit: da8b975a5699
#
Name     : perl-Throwable
Version  : 1.001
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Throwable-1.001.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Throwable-1.001.tar.gz
Summary  : 'a role for classes that can be thrown'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Throwable-license = %{version}-%{release}
Requires: perl-Throwable-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Class::Method::Modifiers)
BuildRequires : perl(Devel::StackTrace)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Moo)
BuildRequires : perl(Moo::Role)
BuildRequires : perl(Role::Tiny)
BuildRequires : perl(Sub::Quote)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution Throwable,
version 1.001:
a role for classes that can be thrown

%package dev
Summary: dev components for the perl-Throwable package.
Group: Development
Provides: perl-Throwable-devel = %{version}-%{release}
Requires: perl-Throwable = %{version}-%{release}

%description dev
dev components for the perl-Throwable package.


%package license
Summary: license components for the perl-Throwable package.
Group: Default

%description license
license components for the perl-Throwable package.


%package perl
Summary: perl components for the perl-Throwable package.
Group: Default
Requires: perl-Throwable = %{version}-%{release}

%description perl
perl components for the perl-Throwable package.


%prep
%setup -q -n Throwable-1.001
cd %{_builddir}/Throwable-1.001

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Throwable
cp %{_builddir}/Throwable-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Throwable/adf867722431e4bc17c7ecaf10de8eb702969afc || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/StackTrace::Auto.3
/usr/share/man/man3/Throwable.3
/usr/share/man/man3/Throwable::Error.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Throwable/adf867722431e4bc17c7ecaf10de8eb702969afc

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
